trigger:
  - main

pool:
  name: muthu
  demands:
    - agent.name -equals muthu

steps:
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      javaHomeOption: 'Path'
      jdkDirectory: 'C:\Program Files\Java\jdk-21'
      mavenVersionOption: 'Default'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish build artifact'
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/target'
      artifact: 'maven-build'
      publishLocation: 'pipeline'
